let nameList = [
    'Time', 'Past', 'Future', 'Dev',
    'Fly', 'Flying', 'Soar', 'Soaring', 'Power', 'Falling',
    'Fall', 'Jump', 'Cliff', 'Mountain', 'Rend', 'Red', 'Blue',
    'Green', 'Yellow', 'Gold', 'Demon', 'Demonic', 'Panda', 'Cat',
    'Kitty', 'Kitten', 'Zero', 'Memory', 'Trooper', 'XX', 'Bandit',
    'Fear', 'Light', 'Glow', 'Tread', 'Deep', 'Deeper', 'Deepest',
    'Mine', 'Your', 'Worst', 'Enemy', 'Hostile', 'Force', 'Video',
    'Game', 'Donkey', 'Mule', 'Colt', 'Cult', 'Cultist', 'Magnum',
    'Gun', 'Assault', 'Recon', 'Trap', 'Trapper', 'Redeem', 'Code',
    'Script', 'Writer', 'Near', 'Close', 'Open', 'Cube', 'Circle',
    'Geo', 'Genome', 'Germ', 'Spaz', 'Shot', 'Echo', 'Beta', 'Alpha',
    'Gamma', 'Omega', 'Seal', 'Squid', 'Money', 'Cash', 'Lord', 'King',
    'Duke', 'Rest', 'Fire', 'Flame', 'Morrow', 'Break', 'Breaker', 'Numb',
    'Ice', 'Cold', 'Rotten', 'Sick', 'Sickly', 'Janitor', 'Camel', 'Rooster',
    'Sand', 'Desert', 'Dessert', 'Hurdle', 'Racer', 'Eraser', 'Erase', 'Big',
    'Small', 'Short', 'Tall', 'Sith', 'Bounty', 'Hunter', 'Cracked', 'Broken',
    'Sad', 'Happy', 'Joy', 'Joyful', 'Crimson', 'Destiny', 'Deceit', 'Lies',
    'Lie', 'Honest', 'Destined', 'Bloxxer', 'Hawk', 'Eagle', 'Hawker', 'Walker',
    'Zombie', 'Sarge', 'Capt', 'Captain', 'Punch', 'One', 'Two', 'Uno', 'Slice',
    'Slash', 'Melt', 'Melted', 'Melting', 'Fell', 'Wolf', 'Hound',
    'Legacy', 'Sharp', 'Dead', 'Mew', 'Chuckle', 'Bubba', 'Bubble', 'Sandwich', 'Smasher', 'Extreme', 'Multi', 'Universe', 'Ultimate', 'Death', 'Ready', 'Monkey', 'Elevator', 'Wrench', 'Grease', 'Head', 'Theme', 'Grand', 'Cool', 'Kid', 'Boy', 'Girl', 'Vortex', 'Paradox'
];
export function generateRandomName() {
    return nameList[Math.floor(Math.random() * nameList.length)];
};

let messages = [
    "As he looked👀 out the window, he saw a clown walk by.",
    "He waited for the stop sign to turn to a go sign.",
    "Today I heard something new and unmemorable.",
    "I struggle with geography.😪",
    "I love bacon, beer, birds, and baboons.",
    "😍😍",
    "👀👀",
    "The door swung open to reveal pink giraffes and red elephants.",
    "Erin accidentally created a new universe.🤣",
    "He never understood why what, when, and where left out who.",
    "😍✨",
    "She used her own hair in the soup to give it more flavor😑",
    "Can I write random sentences?",
    "Hello everyone✨✨",
    "What's up",
    "Let's goo people🔥🔥",
    "👍👍",
    "Jai Hind!",
    "Np",
    "🚀🚀🚀",
    "Jack loves candy too much😁",
    "She says she has the ability to hear the soundtrack of your life.",
    "There was no telling what thoughts would come from the machine.",
    "She had the gift of being able to paint songs.",
    "🙌✨",
    "😂😂",
    "He stomped on his fruit loops and thus became a cereal killer.💀",
    "I want a giraffe, but I'm a turtle eating waffles.",
    "She was too short to see over the fence.😂",
    "The sight of his goatee made me want to run and hide under my sister -in -law's bed.",
    "Please tell me you don't work in a morgue.",
    "🤔🤔",
    "I'd always thought lightning was something only I could see.👀",
    "He figured a few sticks of dynamite were easier than a fishing pole to catch fish.",
    "So long and thanks for the fish.👀",
    "🚀🚀🙌",
    "I met an interesting turtle while the song on the radio blasted away.",
    "As the rental car rolled to a stop on the dark road, her fear increased by the moment.💀",
    "Car safety systems have come a long way, but he was out to prove they could be outsmarted.",
    "We need to rent a room for our party.",
    "🎁🎁",
    "Happiness can be found in the depths of chocolate pudding.",
    "A good example of a useful vegetable is medicinal rhubarb.",
    "Pat ordered a ghost pepper pie.",
    "Nudist colonies shun fig - leaf couture.",
    "🎉🎉🎉🎉",
    "The random sentence generator generated a random sentence about a random sentence.",
    "He decided water - skiing on a frozen lake wasn’t a good idea.🤷‍♂️",
    "The gloves protect my feet from excess work.",
    "Nobody loves a pig wearing lipstick.",
    "🛒🛒✨",
    "Jason lived his life by the motto, Anything worth doing is worth doing poorly.",
    "She was only made the society president because she can whistle with her toes.",
    "Ok👍",
    "✔✔",
]

export function generateRandomMessage() {
    return messages[Math.floor(Math.random() * messages.length)];
}